[manifest]
version = "1.0.0"
dump_lua = true
priority = 5


[[patches]] # https://github.com/thefaketh30ne/grab-bag/blob/main/lovely/jokers.toml#L8-L16
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.06*G.SETTINGS.GAMESPEED, blockable = false, blocking = false, func = function()'''
position = "before"
payload = '''
SMODS.calculate_context{wheel_of_fortune_fail = true}
'''