EF.vars.minigames.parlor.boxes = {"Blue", "White", "Yellow"}
EF.vars.minigames.parlor.box_colors = {G.C.BLUE, G.C.WHITE, G.C.YELLOW}
EF.vars.minigames.parlor.puzzle_list = {
   {'Only one box is true', 'Only one box contains the rewards', 'The rewards is in the white box', 2},
   {'There are four boxes', 'There is only one box ', 'The rewards are in the true box', 3},
   {'The rewards are in the aliensrock discord server', 'The rewards are in this box', 'There are no rewards', 2},
   {'You are playing balatro', 'This box is empty', 'The blue box is true', 2},
   {'This box is empty', 'This box is empty', 'This puzzle is harder than it seems', 3},
   {'The rewards are not in the white box', 'The rewards are not in this box', 'The rewards are in this box', 1},
   {'The rewards are not in this box', 'The blue box is true', 'The rewards are in this box', 2},
   {'This box is the middle box', 'The rewards are in the middle box', 'This box is the middle box', 2},
   {'There are three boxes in this room', 'Two boxes in this room are empty', 'This box is one of the two empty boxes', 3},
   {'This is the blue box', 'The blue box is true', 'The blue box is empty', 1},
   {'The yellow box is yellow', 'The yellow box is true', 'The yellow box is empty', 3},
   {'This is the yellow box', 'This is the yellow box', 'The yellow box is not empty', 3},
   {'The other two boxes are true', 'The other two boxes are blue', 'The other two boxes are empty', 3},
   {'The yellow box contains the rewards', 'This box and the blue box are empty', 'All three boxes are empty', 3},
   {'Only one box is true', 'The yellow box contains the rewards', 'The blue box contains the rewards', 2},
   {'There are two true boxes', 'There are two empty boxes', 'This box is empty', 3},
   {'rewards are in both the yellow box and the white box', 'rewards are in both the blue box and the yellow box', 'rewards are not in the white box or the blue box', 3},
   {'The yellow box is true', 'The rewards are in the true box', 'The blue box is true', 2},
   {'The yellow box is false', 'The yellow box is true', 'A false box contains the rewards', 1},
   {'The white box is true', 'The other two boxes are false', 'The other two boxes are empty', 3},
   {'The rewards are in the false box', 'The rewards are in the false box', 'Only one of the other boxes is false', 3},
   {'This box is the white box', 'This box is the yellow box', 'The blue box contains the rewards', 1},
   {'The rewards are in this box', 'The rewards are in a box next to this box', 'The rewards are in the blue box', 3},
   {'A box next to this box contains rewards', 'Both boxes next to this box contain rewards', 'A box next to this box is true', 2},
   {'Boxes next to this box contain rewards', 'Boxes next to this box contain rewards', 'Boxes next to this box contain rewards', 2},
   {'One of the other boxes is false', 'You will open this box and find it empty', 'The blue box is true', 2},
   {'This box is the yellow box', 'This box is the blue box', 'The box that claims to be yellow has the rewards', 1},
   {'The statement on the white box is true', 'There is a second wind-up key in this room*', 'This box and the white box are both empty', 1},
   {'You will open this box and find it empty', 'A true box contains the rewards', 'This box and the white box are both false', 2},
   {'This box is empty', 'A box with a false statement is empty', 'There are two false statements', 2},
   {'Every box is yellow', 'Every box contains rewards', "The statement on one of the other two boxes would be true if you replaced the word 'every' with the word 'this'", 2},
   {'The rewards are in a box with a statement containing the letter "B"', 'The blue box is true', 'The rewards are in a box with a statement containing the letter "U"', 1},
   {'This statement appears on another box', 'The blue box is empty', 'This statement appears on another box', 1},
   {'The rewards are in the white box', 'Statements with the word "white" are always true', 'The statement on the white box is true', 2},
   {'This box and the white box are both empty', 'This box and the blue box are both empty', 'The other two statements have identical wording', 3},
   {'The statement on this box is true', 'The statement on this box is true', 'Boxes that claim to be true contain rewards', 3},
   {'The yellow box is not empty', 'The statement on the yellow box is true', 'A box with a false statement contains the rewards', 1},
   {'The rewards are in the yellow box', 'The rewards are in the white box', 'Only one box displays a true statement', 1},
   {'This box is not blue', 'Every statement with the word blue is false', 'The yellow box and the blue box are empty', 2},
   {'All three statements are false', 'Two statements are false', 'The rewards are in a box with a false statement', 2},
   {'The rewards are not in the box with a unique statement', 'This statement is unique', 'The rewards are not in the box with a unique statement', 2},
   {'The rewards are in the white box', 'A box with a false statement contains the rewards', 'The statement on the white box is true', 1},
   {'The rewards are in another box', 'The truth is on another box', 'The words "another box" are on another box', 1},
   {'There is only one true statement', 'A rewards are in a box with a false statement', 'There are two true statements', 1},
   {'The empty boxes both have true statements', 'The blue box has a true statement', 'This box contains the rewards', 3},
   {'A box with a false statement contains the rewards', 'The statement on the blue box is true', 'The blue box contains the rewards', 3},
   {'The rewards are in the white box', 'The other two statements are both true', 'The rewards are not in the blue box', 3},
   {'The rewards are in the yellow box', 'This statement is of no help at all', 'This box and the blue box are both false', 3},
   {'The rewards are in this box', 'This statement is of no help of all', 'The rewards are in the blue box', 1},
   {'The rewards are in a box with a false statement', 'The blue box is false', 'The white box is false', 2},
   {'The rewards are in the only true box', 'Only one statement is true', 'The blue box contains the rewards', 3},
   {'The rewards are in the only box with a true statement', 'One of the other boxes is true', 'The rewards are in the only box with a false statement', 1},
   {'This box is empty', 'A box with a false statement is empty', 'There are two false statements', 2},
   {'There are two false statements', 'This is the only true statement', 'The white box is empty', 2},
   {'The rewards are not in a box with a true statement', 'The statement on the blue box is true as is this statement', 'The rewards are not in a box with a true statement', 2},
   {'This is the only true box', 'The rewards are in the other box with a true statement', 'One of the other boxes is true', 3},
   {'Only one statement is false', 'Only one statement is true', 'The rewards are in a box with a false statement', 2},
   {'The rewards are in a box with a statement', '[nothing]', 'The white box does not have a statement', 2},
   {'The rewards are in the yellow box', '[nothing]', 'The rewards are in a box with a statement', 1},
   {'A box next to this box contains rewards', '[nothing]', 'A box next to this box displays a false statement', 2},
   {'The rewards are in the box with the word "blue" on it', '[nothing]', 'The rewards are in a box that is actually blue', 3},
   {'One of the other statements is false', 'One of the other boxes contains rewards', "If you replace the word 'one' in the other two statements with 'both' they will bothe be false", 2},
   {'The rewards are on the table behind you', 'The rewards are in this box', 'Every statement claiming where the rewards are is false. The rewards are in the blue box', 2},
   {'The rewards are in the yellow box', 'The rewards are not in this box', 'The statements on the other two boxes are true', 1},
   {'The white box is empty', 'The blue box is false', 'The empty boxes both have false statements', 3},
   {'The empty boxes are both true', 'The empty boxes are both false', 'This is not an empty box', 2},
   {'The true boxes are both empty', 'The false boxes are both true', 'The rewards are in the blue box', 1},
   {'The empty boxes are both true', 'The rewards are in the yellow box', 'This is not an empty box', 3},
   {"This box's statement is both true and false", 'The blue box contains the rewards if its statement is false', "This statement is as true as the white box's statement", 1},
   {'The rewards are in the yellow box', 'Every statement with the word yellow is false', 'The rewards are in the blue box', 3},
   {'The rewards are not in this box', 'The rewards are in this box', 'The white box is true', 3},
   {'One of the other two boxes is false', 'You will open this box and find it empty', 'The blue box is true', 2},
   {'This box is not blue', 'Every statement with the word blue is false', 'The yellow box and blue box are empty', 2},
   {'The box next to this box is false', 'A box next to this box is true', 'The box next to this box contains rewards', 2},
}